## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 0.6
  - nightly

notifications:
  email: false

# https://github.com/travis-ci/travis-ci/issues/4942 workaround
git:
  depth: 99999999

matrix:
  fast_finish: true
  allow_failures:
  - julia: nightly

## uncomment the following lines to override the default test script
#script:
#  - julia -e 'Pkg.clone(pwd())'
#  - julia -e 'Pkg.build("CMB")'
#  - if [ -f test/runtests.jl ]; then
#      julia --check-bounds=yes -e 'Pkg.test("CMB"; coverage=true)'
#    fi

after_success:
  - julia -e 'cd(Pkg.dir("CMB", "test")); include("coverage.jl")'
