# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags for Documenter.jl
    - /^release-.*$/
notifications:
  email: false
cache:
  directories:
    - $HOME/.julia/artifacts

before_script:
  - julia --project -e '
      using Pkg;
      Registry.add(RegistrySpec("General"));
      Registry.add(RegistrySpec(url = "https://github.com/jmert/Registry.jl"));
      include("scripts/test_minver.jl");'

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true

  include:
    - julia: nightly
    - julia: 1.5
      codecov: true
    - julia: 1.4
    - julia: 1.3

    - stage: Documentation
      julia: 1.3
      os: linux
      if: NOT type IN (pull_request)
      script: julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip
