# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.2
  - 1.3
  - nightly
branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags for Documenter.jl
    - /^release-.*$/
notifications:
  email: false

# Dependencies are pinned by a committed Manifest.toml and used for testing
# on release version of Julia. On nightly, unpin all the dependencies (by
# directly deleting Manifest.toml) and test with whatever the latest package
# versions are.
before_script:
  - >
    if [ x"$TRAVIS_JULIA_VERSION" == x"nightly" ]; then
      echo "rm Manifest.toml";
      rm Manifest.toml;
    fi

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - stage: Documentation
      julia: 1.2
      os: linux
      if: NOT type IN (pull_request)
      script: julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip
