name: CompatHelper
on:
  schedule:
    - cron: 18 06 * * *
  workflow_dispatch:
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: "Install CompatHelper"
        run: |
          import Pkg
          name = "CompatHelper"
          uuid = "aa819f21-2bde-4658-8897-bab36330d9b7"
          version = "2"
          Pkg.add(; name, uuid, version)
        shell: julia --color=yes {0}
      - name: "Run CompatHelper"
        run: |
          import CompatHelper, Pkg
          regs = [Pkg.RegistrySpec(name = "General",
                                   uuid = "23338594-aafe-5451-b93e-139f81909106",
                                   url = "https://github.com/JuliaRegistries/General.git"),
                  Pkg.RegistrySpec(name = "JustinWillmert",
                                   uuid = "b03618a4-f3f8-577f-b15b-d9c21dacf23e",
                                   url = "https://github.com/jmert/Registry.jl"),
                 ]
          CompatHelper.main(; registries = regs)
        shell: julia --color=yes {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
          # COMPATHELPER_PRIV: ${{ secrets.COMPATHELPER_PRIV }}
