name: CompatHelper
on:
  schedule:
    - cron: 18 06 * * *
  workflow_dispatch:
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
        run: julia -e '
          using CompatHelper, Pkg
          regs = [Pkg.RegistrySpec(name = "General",
                                   uid = "23338594-aafe-5451-b93e-139f81909106",
                                   url = "https://github.com/JuliaRegistries/General.git"),
                  Pkg.RegistrySpec(name = "JustinWillmert",
                                   uid = "b03618a4-f3f8-577f-b15b-d9c21dacf23e",
                                   url = "https://github.com/jmert/Registry.jl"),
                 ]
          CompatHelper.main(; registries = regs)'
